spring.application.name=Hotel_RestAPI

spring.datasource.url=jdbc:mysql://localhost:3307/hotel_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=quangto123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.signerKey=df31780bf9c65415d7a7de7f614ea6c437551148bd43a858a790e898a078e2e4